# Generated by Django 4.1.7 on 2023-04-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_new_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='address',
        ),
    ]
